### ISSUE TITLE
Why tape?

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/interface-record-store#2]
I don't want to start a discussion about testing frameworks, just wondering why here you are using tape, and in js-ipfs-api for example we are using mocha.

**Comment by daviddias** [comment]
I'm personally a fan of tape, however, the decision was not made of personal taste, of course :) . I've followed the pattern set by https://github.com/maxogden/abstract-blob-store, the first "abstract-" module, which uses tape and in fact makes sense, because if "you" are going to ask someone to import your tests and run them, better make in the most standardized way and since tape is tap, but running in the browser and in Node.js, which is a [Protocol](http://testanything.org/), makes it easier for everyone else to accept.

**Comment by dignifiedquire** [comment]
Okay thanks for the explanation :)
